### PR TITLE
add parameter for printing only unique results

### PR DESCRIPTION
**Pull request by pilate**

### CODE REVIEW

**Comment by pilate** [comment]
Satisfies #167

**Comment by williballenthin** [comment]
i wonder if perhaps this should be the default mode, and a "more advanced mode" (hardcore mode?) that prints duplicates with their different contexts? cc: @mr-tz thoughts?

**Comment by mr-tz** [comment]
Yes, I think enabling it by default makes sense for most users.

**Comment by mr-tz** [comment]
Awesome, thanks. We can expand the advanced behavior based on this now.

**Pull request merged**
