### PR TITLE
Add logging to script creation functions

### PR DESCRIPTION
**Pull request by capnspacehook**
As I was testing generating script files for idapro, radare2 and x64dbg, and I noticed that there was a few print() statements that were messing with my logging. Specifically, in the floss.main.create_(x64dbg/ida/r2)_database() functions. I added an optional parameter to those 3 functions, so Floss's normal behavior remains unchanged, but those who want to log everything in lieu of using print() now can.

### CODE REVIEW

**Comment by capnspacehook** [comment]
@williballenthin I was going to add this to https://github.com/fireeye/flare-floss/pull/292, but you merged it right before I could commit :laughing:

**Comment by williballenthin** [comment]
btw, thanks for taking the time to report and fix this issue, too! We really appreciate the effort :-)

**Comment by capnspacehook** [comment]
No problem! Will change the print statements. No problem, it's a pleasure to give back to such a great project :smiley:

**Comment by capnspacehook** [comment]
Changes made! Should be good to go!

**Comment by capnspacehook** [comment]
Oops, forgot to fix the git conflicts after merging.

**Comment by williballenthin** [comment]
looks good, thanks!

**Pull request merged**
